model_architecture:
  group_nn_widths:
    - 3
    - 4
    - 5
    - 6
  group_nn_depth: 6
  technique_nn_widths:
    - 3
    - 4
    - 5
    - 6
  technique_nn_depth: 6
  nn_output_size: 4

train:
  epochs: 20
  learning_rate: 0.001
  batch_size: 32
