# config file for model1's
model_architecture:
  group_nn_hidden_layer_widths: 32
  group_nn_hidden_layer_depth: 1
  technique_nn_hidden_layer_widths: 64
  technique_nn_hidden_layer_depth: 1
  nn_output_size: 16
  regularizer: ~
  regularizer_weight: ~

train:
  epochs: 50
  learning_rate: 1e-7
  batch_size: 32