# config file for model1's
model_architecture:
  group_nn_hidden_layer_widths: 32
  group_nn_hidden_layer_depth: 3
  technique_nn_hidden_layer_widths: 64
  technique_nn_hidden_layer_depth: 3
  nn_output_size: 16
  regularizer: ~
  regularizer_weight: ~

train:
  epochs: 30
  learning_rate: 0.001
  batch_size: 32
