model_architecture:
  group_nn_hidden_layer_widths: 32
  group_nn_hidden_layer_depth: 7
  technique_nn_hidden_layer_widths: 62
  technique_nn_hidden_layer_depth: 7
  nn_output_size: 16
  regularizer: ~
  regularizer_weight: ~
  initializer: ~
  dropout_rate: 0.5

train:
  epochs: 100
  learning_rate: 1e-6
  batch_size: 16