# config file for model1's
model_architecture:
  group_nn_hidden_layer_widths: 4
  group_nn_hidden_layer_depth: 7
  technique_nn_hidden_layer_widths: 8
  technique_nn_hidden_layer_depth: 7
  nn_output_size: 2
  regularizer: ~
  regularizer_weight: ~

train:
  epochs: 60
  learning_rate: 1e-6
  batch_size: 16