# selected_group_features:
#   - 'software_ID'
# selected_technique_features:
#   - 'platforms'
#   - 'tactics'
#   - 'data_sources'
#   - 'defenses_bypassed'
#   - 'permissions_required'
#   - 'mitigation_ID'
#   - 'detection_name'
#   - 'software_ID'
# include_unused_techniques: False
# # Data splitting ratio for model1
# data_split: 
#   - 0.7
#   - 0.1
#   - 0.1
#   - 0.1
# resampling: 
#   oversample: 1
#   undersample: ~

#### differences from m1_1 / previous config
# loss = keras.losses.BinaryFocalCrossentropy (from_logits= True, 
                                                #  apply_class_balancing= True,
                                                #  alpha = 0.25, 
                                                #  gamma = 2.5 )
# validation data from training is from cv dataset (not train_cv dataset)
# 
#### The config above is NOT used for training, only for context.
model_architecture:
  group_nn_hidden_layer_widths: 64
  group_nn_hidden_layer_depth: 4
  technique_nn_hidden_layer_widths: 128
  technique_nn_hidden_layer_depth: 4
  nn_output_size: 32
  regularizer: ~
  regularizer_weight: ~
  initializer: ~
  dropout_rate: 0.2
  masking: True

train:
  epochs: 100
  learning_rate:  1e-6
  batch_size: 32
  class_weights: 
    0: 1.0
    1: 1.0
