model_architecture:
  group_nn_hidden_layer_widths: 32
  group_nn_hidden_layer_depth: 4
  technique_nn_hidden_layer_widths: 128
  technique_nn_hidden_layer_depth: 4
  nn_output_size: 16
  regularizer: ~
  regularizer_weight: ~
  initializer: he
  dropout_rate: 0.4
  masking: False

train:
  epochs: 100
  learning_rate:  1e-5
  batch_size: 16
  class_weights: 
    0: 1.0
    1: 1.0