# config file for model1's
model_architecture:
  group_nn_hidden_layer_widths: 64
  group_nn_hidden_layer_depth: 5
  technique_nn_hidden_layer_widths: 128
  technique_nn_hidden_layer_depth: 5
  nn_output_size: 32
  regularizer: ~
  regularizer_weight: ~

train:
  epochs: 20
  learning_rate: 1e-6
  batch_size: 16