# config file for model1's
model_architecture:
  group_nn_widths: 128
  group_nn_depth: 3
  technique_nn_widths: 256
  technique_nn_depth: 3
  nn_output_size: 32
  regularizer: ~
  regularizer_weight: ~

train:
  epochs: 1
  learning_rate: 0.001
  batch_size: 32
