# config file for model1's
model_architecture:
  group_nn_widths:
    - 256
    - 128
    - 64
    - 32
  group_nn_depth: 6
  technique_nn_widths:
    - 128
    - 64
    - 32
  technique_nn_depth: 5
  nn_output_size: 32

train:
  epochs: 30
  learning_rate: 0.001
  batch_size: 32
