# config file for model1's
model_architecture:
  group_nn_hidden_layer_widths: 32
  group_nn_hidden_layer_depth: 2
  technique_nn_hidden_layer_widths: 64
  technique_nn_hidden_layer_depth: 2
  nn_output_size: 8
  regularizer: l2
  regularizer_weight: 1e6

train:
  epochs: 60
  learning_rate: 1e-6
  batch_size: 16